export const documentMapping: Record<string, { formKodu: string; title: string; type: number }> = {
    "1.1": { formKodu: "KysBelgelendirmePolitikasi", title: "1.1 Belgelendirme Politikası Beyanı", type: 1 },
    "1.2": { formKodu: "KysKaliteYonetimSistemiEsasBelgesi", title: "1.2 Kalite Yönetim Sistemi 'Esas' Belgesi", type: 1 },
    "1.3": { formKodu: "KysDenetimSirketininYapisi", title: "1.3 Denetim Şirketinin Yapısı", type: 1 },
    "3.1": { formKodu: "KysUstYonetimPolitikasi", title: "3.1 Üst Yönetim ve Liderlik Yapısı Politikası Beyanı", type: 1 },
    "3.2": { formKodu: "KysSorumluluklarinVerilmesi", title: "3.2 Sorumlulukların Verilmesi", type: 1 },
    "4.1": { formKodu: "EtikHukumlerPolitikaBeyani", title: "4.1 Etik Hükümler Politikası Beyanı", type: 1 },
    "4.2": { formKodu: "YillikBagimsizlikTaahhudu", title: "4.2 Yıllık Bağımsızlık Taahhüdü", type: 1 },
    "4.3": { formKodu: "KysBagimsizlikSorunlariCozumu", title: "4.3 Bağımsızlıkla İlgili Sorunları Çözüme Kavuşturma Formu", type: 1 },
    "5.1": { formKodu: "KysMusteriIliskisiPolitikasi", title: "5.1 Müşteri İlişkisinin ve Belirli Bir Sözleşmenin Kabulü ve Devam Ettirilmesi Politikası Beyanı", type: 1 },
    "5.2": { formKodu: "KysMusteriArastirmaSorulari", title: "5.2 Müşteri Araştırma Soruları", type: 1 },
    "5.3": { formKodu: "KysYeniMusteriFormu", title: "5.3 Yeni Müşteri Formu", type: 2 },
    "5.4": { formKodu: "KysEtikMektubu", title: "5.4 Etik Mektubu", type: 1 },
    "5.5": { formKodu: "KysYeniMusteriKabulKontrolListesi", title: "5.5 Yeni Müşteri Kabulü İçin Kontrol Listesi", type: 1 },
    "5.6": { formKodu: "KysDevamEdenMusteriKontrolListesi", title: "5.6 Devam Eden Müşteri İçin Kontrol Listesi", type: 1 },
    "5.7": { formKodu: "KysMusteriBirakmaFormu", title: "5.7 Müşteri Bırakma Formu", type: 2 },
    "5.8": { formKodu: "KysMusteriBirakmaMektubu", title: "5.8 Müşteri Bırakma Mektubu", type: 2 },
    "6.1": { formKodu: "KysDenetiminYurutulmesiPolitikasi", title: "6.1 Denetimin Yürütülmesi Politikası Beyanı", type: 1 },
    "6.2": { formKodu: "KysCalismaKontrolFormu", title: "6.2 Çalışma Kontrol Formu", type: 2 },
    "6.3": { formKodu: "KysUzmanCalismalarininKullanilmasi", title: "6.3 Uzman Çalışmalarının Kullanılması", type: 3 },
    "6.4": { formKodu: "KysDisUzmanKontrolListesi", title: "6.4 Dış Uzmanların Kullanılmasına İlişkin Kontrol Listesi", type: 2 },
    "6.5": { formKodu: "KysGorusFarkliliklarininCozumu", title: "6.5 Görüş Farklılıklarının Çözüme Kavuşturulması", type: 2 },
    "6.6": { formKodu: "KysDenetimKaliteGozdenGecirme", title: "6.6 Denetimin Kalitesinin Gözden Geçirilmesi Formu", type: 3 },
    "7.1": { formKodu: "KysKaynaklarPolitikasi", title: "7.1 Kaynaklar Politikası Beyanı", type: 1 },
    "7.2": { formKodu: "KysIsTanimlari", title: "7.2 İş Tanımları", type: 2 },
    "7.3": { formKodu: "KysAdayGorusmeKontrolListesi", title: "7.3 Aday Görüşme ve Değerlendirme Kontrol Listesi", type: 2 },
    "7.4": { formKodu: "KysYeniCalisanOryantasyonKontrolListesi", title: "7.4 Yeni Çalışan Oryantasyon Kontrol Listesi", type: 2 },
    "7.5": { formKodu: "KysProfesyonelCalisanPerformansi", title: "7.5 Profesyonel Çalışanların Performansının Değerlendirilmesi", type: 2 },
    "7.6": { formKodu: "KysIdariCalisanPerformansi", title: "7.6 İdari Çalışanların Performansının Gözden Geçirilmesi", type: 2 },
    "7.7": { formKodu: "KysEgitimVeGelisimKayitlari", title: "7.7 Eğitim ve Gelişim Kayıtları", type: 2 },
    "7.8": { formKodu: "KysTeknolojiSatinAlmaTalepFormu", title: "7.8 Teknoloji Satın Alma Talep Formu", type: 2 },
    "7.9": { formKodu: "KysYeniHizmetSaglayiciTalepFormu", title: "7.9 Yeni Hizmet Sağlayıcı Talep Formu", type: 2 },
    "8.1": { formKodu: "KysBilgiVeIletisimPolitikasi", title: "8.1 Bilgi ve İletişim Politikası Beyanı", type: 1 },
    "8.2": { formKodu: "KysBilgiVeIletisimKulturDegerlendirmesi", title: "8.2 Kültür Değerlendirmesi - Kalite", type: 2 },
    "9.1": { formKodu: "KysIzlemeVeDuzeltmeSureciRehberi", title: "9.1 İzleme ve Düzeltme Süreci Rehberi", type: 1 },
    "9.2": { formKodu: "KysIzlemeVeDuzeltmePolitikasi", title: "9.2 İzleme ve Düzeltme Süreci Politikası Beyanı", type: 1 },
    "9.3": { formKodu: "KysDenetiminGozdenGecirilmesiFormu", title: "9.3 Denetimin Gözden Geçirilmesi Formu", type: 2 },
    "9.4": { formKodu: "KysSistemDegerlendirmesi", title: "9.4 Sistem Değerlendirmesi", type: 2 },
    "9.5": { formKodu: "KysMusteriSikayetKaydi", title: "9.5 Müşteri Şikâyet Kaydı", type: 2 },
    "9.6": { formKodu: "KysBulgularKaydi", title: "9.6 Bulgular Kaydı", type: 2 },
    "9.7": { formKodu: "KysEksiklikDegerlendirme", title: "9.7 Eksiklik Değerlendirme Çalışma Sayfası", type: 2 },
};

export const riskMatrixSections = [
    {
        label: "1. Üst Yönetim",
        kategoriKodu: "UstYonetim",
        title: "Üst Yönetim ve Liderlik Yapısı - Risk Matrisi",
        documents: ["3.1", "3.2", "7.5", "1.2", "1.1", "9.2", "7.6", "1.3"]
    },
    {
        label: "2. Etik Hükümler",
        kategoriKodu: "EtikHukumler",
        title: "Etik Hükümler - Risk Matrisi",
        documents: ["4.1", "4.2", "4.3", "9.5", "7.7", "5.2", "5.4", "7.9", "6.3", "6.4"]
    },
    {
        label: "3. Müşteri İlişkisi",
        kategoriKodu: "MusteriIliskisi",
        title: "Müşteri İlişkisinin ve Sözleşmenin Kabulü - Risk Matrisi",
        documents: ["5.1", "5.2", "5.3", "5.4", "5.5", "5.6", "3.1", "8.2", "7.5"]
    },
    {
        label: "4. Denetimin Yürütülmesi",
        kategoriKodu: "DenetiminYurutulmesi",
        title: "Denetimin Yürütülmesi - Risk Matrisi",
        documents: ["6.1", "6.2", "6.3", "6.4", "5.2", "5.3", "4.1", "6.6", "7.5", "6.5", "9.3", "1.1"]
    },
    {
        label: "5. Kaynaklar",
        kategoriKodu: "Kaynaklar",
        title: "Kaynaklar - Risk Matrisi",
        documents: ["7.1", "7.3", "7.4", "7.2", "7.7", "7.5", "9.3", "7.9", "7.8", "8.1"]
    },
    {
        label: "6. Bilgi ve İletişim",
        kategoriKodu: "BilgiVeIletisim",
        title: "Bilgi ve İletişim - Risk Matrisi",
        documents: ["7.1", "7.7", "8.1", "7.8", "8.2", "6.3", "6.4", "9.3"]
    }
];

export const KYS_PATH_TO_FORM_KODU: Record<string, string> = {
    "/Kys/Belgelendirme/BelgelendirmePolitikasi": "KysBelgelendirmePolitikasi",
    "/Kys/Belgelendirme/KaliteYonetimSistemiEsasBelgesi": "KysKaliteYonetimSistemiEsasBelgesi",
    "/Kys/Belgelendirme/DenetimSirketininYapisi": "KysDenetimSirketininYapisi",
    "/Kys/RiskDegerlendirmeSureci/PolitikaBeyani": "KysRiskDegerlendirmePolitikasi",
    "/Kys/UstYonetimVeLiderlik/PolitikaBeyani": "KysUstYonetimPolitikasi",
    "/Kys/UstYonetimVeLiderlik/SorumluluklarinVerilmesi": "KysSorumluluklarinVerilmesi",
    "/Kys/EtikHukumler/PolitikaBeyani": "KysEtikHukumlerPolitikasi",
    "/Kys/EtikHukumler/YillikBagimsizlikTaahhudu": "KysYillikBagimsizlikTaahhudu",
    "/Kys/EtikHukumler/BagimsizlikSorunlariCozumu": "KysBagimsizlikSorunlariCozumu",
    "/Kys/MusteriIliskisi/PolitikaBeyani": "KysMusteriIliskisiPolitikasi",
    "/Kys/MusteriIliskisi/MusteriArastirmaSorulari": "KysMusteriArastirmaSorulari",
    "/Kys/MusteriIliskisi/YeniMusteriFormu": "KysYeniMusteriFormu",
    "/Kys/MusteriIliskisi/EtikMektubu": "KysEtikMektubu",
    "/Kys/MusteriIliskisi/YeniMusteriKabulKontrolListesi": "KysYeniMusteriKabulKontrolListesi",
    "/Kys/MusteriIliskisi/DevamEdenMusteriKontrolListesi": "KysDevamEdenMusteriKontrolListesi",
    "/Kys/MusteriIliskisi/MusteriBirakmaFormu": "KysMusteriBirakmaFormu",
    "/Kys/MusteriIliskisi/MusteriBirakmaMektubu": "KysMusteriBirakmaMektubu",
    "/Kys/DenetiminYurutulmesi/PolitikaBeyani": "KysDenetiminYurutulmesiPolitikasi",
    "/Kys/DenetiminYurutulmesi/CalismaKontrolFormu": "KysCalismaKontrolFormu",
    "/Kys/DenetiminYurutulmesi/UzmanCalismalarininKullanilmasi": "KysUzmanCalismalarininKullanilmasi",
    "/Kys/DenetiminYurutulmesi/DisUzmanKontrolListesi": "KysDisUzmanKontrolListesi",
    "/Kys/DenetiminYurutulmesi/GorusFarkliliklarininCozumu": "KysGorusFarkliliklarininCozumu",
    "/Kys/DenetiminYurutulmesi/DenetimKaliteGozdenGecirme": "KysDenetimKaliteGozdenGecirme",
    "/Kys/Kaynaklar/PolitikaBeyani": "KysKaynaklarPolitikasi",
    "/Kys/Kaynaklar/IsTanimlari": "KysIsTanimlari",
    "/Kys/Kaynaklar/AdayGorusmeKontrolListesi": "KysAdayGorusmeKontrolListesi",
    "/Kys/Kaynaklar/YeniCalisanOryantasyonKontrolListesi": "KysYeniCalisanOryantasyonKontrolListesi",
    "/Kys/Kaynaklar/ProfesyonelCalisanPerformansi": "KysProfesyonelCalisanPerformansi",
    "/Kys/Kaynaklar/IdariCalisanPerformansi": "KysIdariCalisanPerformansi",
    "/Kys/Kaynaklar/EgitimVeGelisimKayitlari": "KysEgitimVeGelisimKayitlari",
    "/Kys/Kaynaklar/TeknolojiSatinAlmaTalepFormu": "KysTeknolojiSatinAlmaTalepFormu",
    "/Kys/Kaynaklar/YeniHizmetSaglayiciTalepFormu": "KysYeniHizmetSaglayiciTalepFormu",
    "/Kys/BilgiVeIletisim/PolitikaBeyani": "KysBilgiVeIletisimPolitikasi",
    "/Kys/BilgiVeIletisim/KulturDegerlendirmesi": "KysBilgiVeIletisimKulturDegerlendirmesi",
    "/Kys/IzlemeVeDuzeltme/SureciRehberi": "KysIzlemeVeDuzeltmeSureciRehberi",
    "/Kys/IzlemeVeDuzeltme/PolitikaBeyani": "KysIzlemeVeDuzeltmePolitikasi",
    "/Kys/IzlemeVeDuzeltme/DenetiminGozdenGecirilmesi": "KysDenetiminGozdenGecirilmesiFormu",
    "/Kys/IzlemeVeDuzeltme/SistemDegerlendirmesi": "KysSistemDegerlendirmesi",
    "/Kys/IzlemeVeDuzeltme/MusteriSikayetKaydi": "KysMusteriSikayetKaydi",
    "/Kys/IzlemeVeDuzeltme/BulgularKaydi": "KysBulgularKaydi",
    "/Kys/IzlemeVeDuzeltme/EksiklikDegerlendirme": "KysEksiklikDegerlendirme",
};
